# Datasource Grafana -> Wazuh Indexer (OpenSearch)
# Propriétaire : Papa Mamadou Ba
# Plugin requis : grafana-cli plugins install grafana-opensearch-datasource
apiVersion: 1

datasources:
  - name: Wazuh Indexer
    type: grafana-opensearch-datasource
    access: proxy
    url: https://<IP_WAZUH_INDEXER>:9200
    basicAuth: true
    basicAuthUser: admin
    jsonData:
      database: 'wazuh-alerts-*'
      timeField: '@timestamp'
      flavor: opensearch
      version: 2.13.0
      tlsSkipVerify: true
    secureJsonData:
      basicAuthPassword: '${WAZUH_INDEXER_PASSWORD}'
